compuapp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='Home'),
    path('computer_entry/', views.computer_entry, name='computer_entry'),
    path('computer_list/', views.computer_list, name='computer_list'),
    path('computer_list/(?P<id>\d+)/$', views.computer_edit, name='computer_edit'),
    path('computer_list/(?P<id>\d+)/delete$', views.computer_delete, name='computer_delete'),
    path('computerhistory_list/', views.computerhistory_list, name='computerhistory_list'),
    path('accounts/', include('registration.backends.default.urls')),
    path('settings/', views.settings, name='settings'),
    ]

inventario/urls.py
from django.urls import path, include
from django.contrib import admin
from compuapp.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('compuapp.urls')),

]

compuapp/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Operating_system(models.Model):
    operating_system = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.operating_system


class Computer(models.Model):
    computer_name = models.CharField(max_length=30, blank=True)
    IP_address = models.CharField(max_length=30)
    MAC_address = models.CharField(max_length=30)
    operating_system = models.ManyToManyField(Operating_system,max_length=30, blank=True)
    users_name = models.CharField(max_length=30,blank=True)
    location = models.CharField(max_length=30)
    purchase_date = models.DateField('Fecha compra (dd/mm/2023)', auto_now_add=False, auto_now=False, blank=True, null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False, blank=True)
    export_to_CSV = models.BooleanField(default=False)
    def __unicode__(self):
        return self.IP_address + ' ' + self.computer_name


class ComputerHistory(models.Model):
    computer_name = models.CharField(max_length=30, blank=True, null=True)
    IP_address = models.CharField(max_length=30, blank=True, null=True)
    MAC_address = models.CharField(max_length=30, blank=True, null=True)
    operating_system = models.ManyToManyField(Operating_system,max_length=30, blank=True)
    users_name = models.CharField(max_length=30, blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    purchase_date = models.DateField("Purchase Date(mm/dd/2019)", auto_now_add=False, auto_now=False, blank=True,null=True)
    timestamp = models.DateField(auto_now_add=True, auto_now=False, blank=True, null=True)

compuapp/forms.py
from django import forms
from .models import Computer, Operating_system

class ComputerForm(forms.ModelForm):
   class Meta:
        model = Computer
        fields = ['computer_name', 'IP_address', 'MAC_address','operating_system', 'users_name', 'location', 'purchase_date']

   def clean_computer_name(self):  # Validates the Computer Name Field
       computer_name = self.cleaned_data.get('computer_name')
       if (computer_name == ""):
           raise forms.ValidationError('Este campo no puede quedar vacio.')

       '''for instance in Computer.objects.all():
               if instance.computer_name == computer_name:
                  raise forms.ValidationError('El nombre ' + computer_name + ' ya existe.')
       '''
       return computer_name

class ComputerSearchForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = ['computer_name','users_name', 'export_to_CSV']


class OperatingSystemForm(forms.ModelForm):
    class Meta:
        model =  Operating_system
        fields = ['operating_system']

compuapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ComputerForm, ComputerSearchForm, OperatingSystemForm
from .models import Computer, ComputerHistory
from django.http import HttpResponse
import csv
from django.contrib import messages


# Create your views here.
def home(request):
    title = "Bienvenidos, esta es la paginal "
    context ={
    "title" : title,
    }
    return render(request, "base.html", context)

def computer_entry(request):
    title = "Agregar equipo"
    form = ComputerForm(request.POST or None)
    if form.is_valid():
       form.save()
       form.save_m2m()
       messages.success(request, 'Los datos del equipo han sido guardados exitosamente.')
       return redirect("/computer_list")

    context = {
        "title": title,
        "form": form,
        }
    return render(request, "add_computer.html",context)

def computer_list(request):
    title = "Lista de Equipos"
    queryset = Computer.objects.all()
    form = ComputerSearchForm(request.POST or None)
    context = {
        "title": title,
        "queryset": queryset,
        "form": form,
    }
    if request.method == 'POST':
       queryset = Computer.objects.all().order_by('-timestamp').filter(computer_name__icontains=form['computer_name'].value(), users_name__icontains = form['users_name'].value())
       context = {
            "title": title,
            "queryset": queryset,
            "form": form,
       }
       if form['export_to_CSV'].value() == True:
           response = HttpResponse(content_type='text/csv')
           response['Content-Disposition'] = 'attachment; filename="Computer list.csv"'
           writer = csv.writer(response)
           writer.writerow(['COMPUTER NAME', 'IP Address', 'MAC ADDRESS', 'OS', 'USERNAME', 'LOCATION', 'PURCHASE DATE','TIMESTAMP'])
           instance = queryset
           for row in instance:
               writer.writerow(
                   [row.computer_name, row.IP_address, row.MAC_address, row.operating_system.all(), row.users_name,row.location, row.purchase_date, row.timestamp])
           return response

    return render(request, "list_computer.html",context)


def computer_edit(request, id=None):
    instance = get_object_or_404(Computer, id=id)
    form = ComputerForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        form.save_m2m()
        messages.success(request, 'Los datos del equipo han sido guardados exitosamente.')
        return redirect('/computer_list')
    context = {
        "title": 'Editando ' + str(instance.computer_name),
        "instance": instance,
        "form": form,
        }
    return render(request, "add_computer.html", context)

def computer_delete(request, id=None):
    instance = get_object_or_404(Computer, id=id)
    instance.delete()
    return redirect('/computer_list')

def computer_list(request):
    title = "Lista de Equipos"
    queryset = Computer.objects.all()

    context = {
    "title": title,
    "queryset": queryset,
    }
    return render(request, "list_computer.html",context)


def computerhistory_list(request):
    title = 'Historico Movimiento de Equipos'
    queryset = ComputerHistory.objects.all()
    context = {
       "title": title,
       "queryset": queryset,
    }
    return render(request, "computerhistory_list.html",context)

def settings(request):
    title = 'Agregar Sistema Operativo'
    form = OperatingSystemForm(request.POST or None)
    if form.is_valid():
       form.save()
       messages.success(request, 'Los datos han sido guardados satisfactoriamente.')
       return redirect('/computer_list')
    context = {
              "title": title,
              "form": form,
    }
    return render(request, "settings.html",context)

templates/add_computer.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Fixed top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <!-- Favicons -->
    <link rel="apple-touch-icon" href="{% static 'img/favicons/apple-touch-icon.png' %}" sizes="180x180 ">
    <link rel="icon" href="{% static 'img/favicons/favicon-32x32.png" sizes="32x32' %}" type="image/png">
    <link rel="icon" href="{% static 'img/favicons/favicon-16x16.png" sizes="16x16 '%}" type="image/png">
    <link rel="manifest" href="{% static 'img/favicons/manifest.json '%}">
    <link rel="mask-icon" href="{% static 'img/favicons/safari-pinned-tab.svg' %}" color="#563d7c">
    <link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
    <meta name="msapplication-config" content="{% static 'img/favicons/browserconfig.xml' %}">
    <meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
     <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
     <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
     <link href="{% static 'js/jquery-ui-1.13.2/jquery-ui.min.js' %}" rel="stylesheet">
     <link href="{% static 'js/jquery-ui-1.13.2/jquery-ui.structure.min.css' %}" rel="stylesheet">
     <link href="{% static 'js/jquery-ui-1.13.2/jquery-ui.theme.min.css' %}" rel="stylesheet">
  </head>
  <body>
      {% include 'navbar.html'  %}

        <main role="main" class="container">
          <div class="jumbotron">
              <div class="row">
                  {% if request.user.is_authenticated %}

                  <div class="col-sm-4">
                        <h1 class="title">  {{title}}</h1>
                        <form method="post" action="">
                              {% csrf_token %}
                              {{form.as_p}}
                              <input class="btn btn-primary" type="submit" value="Save" />
                        </form>
                  </div>

                  <div class="col-sm-8 aligncenter">
                     <img style="width: 100%" src="/static/img/pc.png">
                  </div>

                  {% else %}Para conectarse haga clic <a href="/accounts/login"> aqui</a>
                  {% endif %}
              </div>
          </div>
        </main>
        <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
        <script src="{% static 'js/jquery-ui-1.13.2/jquery-ui.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
  </body>
</html>

templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Fixed top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="{% static 'img/favicons/apple-touch-icon.png' %}" sizes="180x180 ">
<link rel="icon" href="{% static 'img/favicons/favicon-32x32.png" sizes="32x32' %}" type="image/png">
<link rel="icon" href="{% static 'img/favicons/favicon-16x16.png" sizes="16x16 '%}" type="image/png">
<link rel="manifest" href="{% static 'img/favicons/manifest.json '%}">
<link rel="mask-icon" href="{% static 'img/favicons/safari-pinned-tab.svg' %}" color="#563d7c">
<link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
<meta name="msapplication-config" content="{% static 'img/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
     <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>
  <body>
  {% include 'navbar.html'  %}

    <main role="main" class="container">
      <div class="jumbotron">
        <h1>  {{title}}</h1>
        <p class="lead"></p>

        <div class='col-sm-3'>
            <a class="btn btn-lg btn-primary" href="/docs/4.4/components/navbar/" role="button">Login</a>
         </div>
         <!-- <a class="btn btn-lg btn-primary" href="/docs/4.4/components/navbar/" role="button">Login</a -->

        <div class='col-sm-3'>
            {% block title %}
            {% endblock %}

            {% block content %}
            {% endblock %}
         </div>

      </div>



    </main>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>
</html>

templates/computerhistory_list.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Fixed top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="{% static 'img/favicons/apple-touch-icon.png' %}" sizes="180x180 ">
<link rel="icon" href="{% static 'img/favicons/favicon-32x32.png" sizes="32x32' %}" type="image/png">
<link rel="icon" href="{% static 'img/favicons/favicon-16x16.png" sizes="16x16 '%}" type="image/png">
<link rel="manifest" href="{% static 'img/favicons/manifest.json '%}">
<link rel="mask-icon" href="{% static 'img/favicons/safari-pinned-tab.svg' %}" color="#563d7c">
<link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
<meta name="msapplication-config" content="{% static 'img/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
     <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>
  <body>
  {% include 'navbar.html'  %}

  <main role="main" class="container">
  <div class="jumbotron">

    {% if messages %}
        <ul class="messages">
               {% for message in messages %}
                     <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
               {% endfor %}
       </ul>
    {% endif %}

    <h1 class="title">{{title}}</h1>
    <form method="post" action="">
        {% csrf_token %}
        {{form.as_p}}
     </form>
    <table>
    <tr>
        <th>#</th>
        <th>NOMBRE PC</th>
        <th>DIRECCION IP</th>
        <th>MAC</th>
        <th>S.O.</th>
        <th>USUARIO</th>
        <th>UBICACION</th>
        <th>OPCIONES</th>
    </tr>
    {% for instance in queryset %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td><a href="{% url 'computer_edit' id=instance.id %}"> {{instance.computer_name}}</td>
        <td>{{instance.IP_address}}</td>
        <td>{{instance.MAC_address}}</td>
        <td>{{instance.operating_system.all}}</td>
        <td>{{instance.users_name}}</td>
        <td>{{instance.location}}</td>
        <td><a href="{% url 'computer_delete' id=instance.id %}">Eliminar</a></td>
    </tr>
    {% endfor %}
    </table>
  </div>
</main>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>
</html>

templates/home.html
{% load static %}

<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Fixed top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="{% static 'img/favicons/apple-touch-icon.png' %}" sizes="180x180 ">
<link rel="icon" href="{% static 'img/favicons/favicon-32x32.png" sizes="32x32' %}" type="image/png">
<link rel="icon" href="{% static 'img/favicons/favicon-16x16.png" sizes="16x16 '%}" type="image/png">
<link rel="manifest" href="{% static 'img/favicons/manifest.json '%}">
<link rel="mask-icon" href="{% static 'img/favicons/safari-pinned-tab.svg' %}" color="#563d7c">
<link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
<meta name="msapplication-config" content="{% static 'img/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
     <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>
  <body>
  {% include 'navbar.html'  %}

    <main role="main" class="container">
      <div class="jumbotron">
        <h1>  {{title}}</h1>
        <p class="lead">Esta es nuestra pagina principal.</p>
        <a class="btn btn-lg btn-primary" href="/docs/4.4/components/navbar/" role="button">Login</a>
      </div>

    </main>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>
</html>

templates/home_old.html
{% load static %}

<html>
    <head>
        <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
    </head>
     {{title}}
</html>

templates/list_computer.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Fixed top navbar example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="{% static 'img/favicons/apple-touch-icon.png' %}" sizes="180x180 ">
<link rel="icon" href="{% static 'img/favicons/favicon-32x32.png" sizes="32x32' %}" type="image/png">
<link rel="icon" href="{% static 'img/favicons/favicon-16x16.png" sizes="16x16 '%}" type="image/png">
<link rel="manifest" href="{% static 'img/favicons/manifest.json '%}">
<link rel="mask-icon" href="{% static 'img/favicons/safari-pinned-tab.svg' %}" color="#563d7c">
<link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">
<meta name="msapplication-config" content="{% static 'img/favicons/browserconfig.xml' %}">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
     <link href="{% static 'css/stylesheet.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">
  </head>
  <body>
  {% include 'navbar.html'  %}

  {% if request.user.is_authenticated %}
  <main role="main" class="container">

      <div class="jumbotron">

        {% if messages %}
            <ul class="messages">
                   {% for message in messages %}
                         <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                   {% endfor %}
           </ul>
        {% endif %}

        <h1 class="title">{{title}}</h1>
          <div class="flt-search">
            <form method="post" action="">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn-primary" type="submit" value="Search" />
            </form>
          </div>
        <table>
        <tr>
            <th>#</th>
            <th>NOMBRE PC</th>
            <th>DIRECCION IP</th>
            <th>MAC</th>
            <th>S.O.</th>
            <th>USUARIO</th>
            <th>UBICACION</th>
            <th>OPCIONES</th>
        </tr>
        {% for instance in queryset %}
        <tr>
            <td>{{forloop.counter}}</td>
            {% if perms.djangoapp.change_computer %}
               <td><a href="{% url 'computer_edit' id=instance.id %}" data-toggle="tooltip" title="Editar este registro"> {{instance.computer_name}}</td>
            {% else %}
               <td>{{instance.computer_name}}</td>
            {% endif %}
            <td>{{instance.IP_address}}</td>
            <td>{{instance.MAC_address}}</td>
            <td>{{instance.operating_system.all}}</td>
            <td>{{instance.users_name}}</td>
            <td>{{instance.location}}</td>
            {% if perms.djangoapp.add_computer %}
               <td><a href="{% url 'computer_delete' id=instance.id %}" data-toggle="tooltip" title="Eliminar este registro"><img src="{% static 'img/del.png' %}"></a></td>
            {% else %}
               <td></td>
            {% endif %}
        </tr>
        {% endfor %}
        </table>
      </div>

  </main>
{% else %}Para conectarse haga clic <a href="/accounts/login"> aqui</a>
{% endif %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script></body>
</html>